### PR TITLE
Use dyn Trait over the old syntax

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
@est31 pointed this out on IRC

### CODE REVIEW

**Comment by Centril** [comment]
cc @steveklabnik 

This might be intentional?
The `impl Trait` section is before `dyn Trait` and has therefore not introduced the `dyn Trait` syntax yet.
Might be good avoiding introducing two things at once.

**Comment by est31** [comment]
Maybe the section order can be flipped?

**Comment by Centril** [comment]
@est31 I'll wait a bit for Steve's input first, but that seems reasonable :)

**Comment by steveklabnik** [comment]
That was my intention, but however, it's probably best to do this, but also add a little

    > Note: see the `dyn Trait` section for an explanation of that syntax

maybe?

**Comment by Centril** [comment]
@steveklabnik SGTM 👍

**Comment by Mark-Simulacrum** [comment]
Okay, I've flipped the order here.

**Comment by Centril** [comment]
LGTM, thanks!

**Pull request merged**
