### PR TITLE
Updated status of `raw_identifiers` feature

### PR DESCRIPTION
**Pull request by alexreg**
Depends on https://github.com/rust-lang/rust/pull/53236.

### CODE REVIEW

**Comment by Centril** [comment]
@alexreg can you fix the conflicts please? :)

**Comment by alexreg** [comment]
@Centril Done!

**Comment by Centril** [comment]
@alexreg  unfortunately the build fails ;)

**Comment by alexreg** [comment]
@Centril Yeah, it's just waiting on https://github.com/rust-lang/rust/pull/53236 now (which removes the need for the feature gate for raw idents, of course). Just look how many failed roll-up merge attempts there have been. 😄

**Comment by Centril** [comment]
@alexreg Jesus...!  Oh well; please cc me when it is OK to merge this :)

**Comment by alexreg** [comment]
@Centril Haha yes. I'll try to remember! My Rust Book PR is also blocked on the main stabilisation PR so...

**Comment by steveklabnik** [comment]
Thank you!

**Pull request merged**
