### PR TITLE
Ask people to test the new uniform paths variant when transitioning

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Comment by Centril** [comment]
Seems travis is unhappy :(

**Comment by joshtriplett** [comment]
@Centril Looks like it's going to be unhappy until nightly has the feature available, which is probably a good thing.

**Comment by Centril** [comment]
@joshtriplett  Indeed; The changes themselves look mostly good but I'll do a quick review since it's no rush :)

**Comment by aturon** [comment]
Passes Travis now. Merging!

**Pull request merged**
